In [10]:
import pandas as pd
import sqlite3
from tqdm.notebook import tqdm
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

# hopteam

In [12]:
hop_team = pd.read_csv('./data/DocGraph/Docgraph_Hop_Teaming_2018.csv', nrows = 100)
hop_team.head(5)

,from_npi,to_npi,patient_count,transaction_count,average_day_wait,std_day_wait
0,1508062167,1730166109,350,370,53.922,72.612
1,1508065640,1730166109,25,25,49.800,55.006
2,1508052093,1730166109,16,16,109.500,70.593
3,1508172545,1730166109,14,14,103.357,75.483
4,1508285131,1730166109,20,21,89.952,89.880

In [13]:
hop_team=hop_team.reset_index().rename(columns={'index': 'referral_id'})
hop_team.head(5)

,referral_id,from_npi,to_npi,patient_count,transaction_count,average_day_wait,std_day_wait
0,0,1508062167,1730166109,350,370,53.922,72.612
1,1,1508065640,1730166109,25,25,49.800,55.006
2,2,1508052093,1730166109,16,16,109.500,70.593
3,3,1508172545,1730166109,14,14,103.357,75.483
4,4,1508285131,1730166109,20,21,89.952,89.880

In [14]:
from_npi=hop_team[['referral_id', 'from_npi']]
to_npi=hop_team[['referral_id', 'to_npi']]
referrals= hop_team[['referral_id', 'patient_count', 'transaction_count', 'average_day_wait', 'std_day_wait']]

# cbsa

In [16]:
cbsa_zip=pd.read_excel('data/ZIP_CBSA_122021.xlsx')
cbsa_zip.head(5)

,zip,cbsa,usps_zip_pref_city,usps_zip_pref_state,res_ratio,bus_ratio,oth_ratio,tot_ratio
0,683,41900,SAN GERMAN,PR,0.999842,1.0,1.0,0.999855
1,683,32420,SAN GERMAN,PR,0.000158,0.0,0.0,0.000145
2,923,41980,SAN JUAN,PR,1.000000,1.0,1.0,1.000000
3,1010,44140,BRIMFIELD,MA,0.976896,1.0,1.0,0.977816
4,1010,49340,BRIMFIELD,MA,0.023104,0.0,0.0,0.022184

In [17]:
cbsa_zip['zip']=cbsa_zip['zip'].astype(str).str.zfill(5)
cbsa_zip['cbsa']=cbsa_zip['cbsa'].astype(str).str.zfill(5)

In [18]:
cbsa_zip=cbsa_zip.rename(columns={'usps_zip_pref_city': 'city',
                                 'usps_zip_pref_state': 'state'})

cbsa_zip.head(5)

     zip   cbsa        city state  res_ratio  bus_ratio  oth_ratio  tot_ratio
0  00683  41900  SAN GERMAN    PR   0.999842        1.0        1.0   0.999855
1  00683  32420  SAN GERMAN    PR   0.000158        0.0        0.0   0.000145
2  00923  41980    SAN JUAN    PR   1.000000        1.0        1.0   1.000000
3  01010  44140   BRIMFIELD    MA   0.976896        1.0        1.0   0.977816
4  01010  49340   BRIMFIELD    MA   0.023104        0.0        0.0   0.022184

# NPI

In [28]:
profile = pd.read_csv('./data/NPPES/npidata_pfile_20050523-20220213.csv', nrows = 100)

In [30]:
profile.head(2)

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider Other Organization Name,Provider Other Organization Name Type Code,Provider Other Last Name,Provider Other First Name,Provider Other Middle Name,Provider Other Name Prefix Text,Provider Other Name Suffix Text,Provider Other Credential Text,Provider Other Last Name Type Code,Provider First Line Business Mailing Address,Provider Second Line Business Mailing Address,Provider Business Mailing Address City Name,Provider Business Mailing Address State Name,Provider Business Mailing Address Postal Code,Provider Business Mailing Address Country Code (If outside U.S.),Provider Business Mailing Address Telephone Number,Provider Business Mailing Address Fax Number,Provider First Line Business Practice Location Address,Provider Second Line Business Practice Location Address,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Postal Code,Provider Business Practice Location Address Country Code (If outside U.S.),Provider Business Practice Location Address Telephone Number,Provider Business Practice Location Address Fax Number,Provider Enumeration Date,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date,Provider Gender Code,Authorized Official Last Name,Authorized Official First Name,Authorized Official Middle Name,Authorized Official Title or Position,Authorized Official Telephone Number,Healthcare Provider Taxonomy Code_1,Provider License Number_1,Provider License Number State Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Provider License Number_2,Provider License Number State Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Provider License Number_3,Provider License Number State Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Provider License Number_4,Provider License Number State Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Provider License Number_5,Provider License Number State Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Provider License Number_6,Provider License Number State Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Provider License Number_7,Provider License Number State Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Provider License Number_8,Provider License Number State Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Provider License Number_9,Provider License Number State Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Provider License Number_10,Provider License Number State Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Provider License Number_11,Provider License Number State Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Provider License Number_12,Provider License Number State Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Provider License Number_13,Provider License Number State Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Provider License Number_14,Provider License Number State Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Provider License Number_15,Provider License Number State Code_15,Healthcare Provider Primary Taxonomy Switch_15,Other Provider Identifier_1,Other Provider Identifier Type Code_1,Other Provider Identifier State_1,Other Provider Identifier Issuer_1,Other Provider Identifier_2,Other Provider Identifier Type Code_2,Other Provider Identifier State_2,Other Provider Identifier Issuer_2,Other Provider Identifier_3,Other Provider Identifier Type Code_3,Other Provider Identifier State_3,Other Provider Identifier Issuer_3,Other Provider Identifier_4,Other Provider Identifier Type Code_4,Other Provider Identifier State_4,Other Provider Identifier Issuer_4,Other Provider Identifier_5,Other Provider Identifier Type Code_5,Other Provider Identifier State_5,Other Provider Identifier Issuer_5,Other Provider Identifier_6,Other Provider Identifier Type Code_6,Other Provider Identifier State_6,Other Provider Identifier Issuer_6,Other Provider Identifier_7,Other Provider Identifier Type Code_7,Other Provider Identifier State_7,Other Provider Identifier Issuer_7,Other Provider Identifier_8,Other Provider Identifier Type Code_8,Other Provider Identifier State_8,Other Provider Identifier Issuer_8,Other Provider Identifier_9,Other Provider Identifier Type Code_9,Other Provider Identifier State_9,Other Provider Identifier Issuer_9,Other Provider Identifier_10,Other Provider Identifier Type Code_10,Other Provider Identifier State_10,Other Provider Identifier Issuer_10,Other Provider Identifier_11,Other Provider Identifier Type Code_11,Other Provider Identifier State_11,Other Provider Identifier Issuer_11,Other Provider Identifier_12,Other Provider Identifier Type Code_12,Other Provider Identifier State_12,Other Provider Identifier Issuer_12,Other Provider Identifier_13,Other Provider Identifier Type Code_13,Other Provider Identifier State_13,Other Provider Identifier Issuer_13,Other Provider Identifier_14,Other Provider Identifier Type Code_14,Other Provider Identifier State_14,Other Provider Identifier Issuer_14,Other Provider Identifier_15,Other Provider Identifier Type Code_15,Other Provider Identifier State_15,Other Provider Identifier Issuer_15,Other Provider Identifier_16,Other Provider Identifier Type Code_16,Other Provider Identifier State_16,Other Provider Identifier Issuer_16,Other Provider Identifier_17,Other Provider Identifier Type Code_17,Other Provider Identifier State_17,Other Provider Identifier Issuer_17,Other Provider Identifier_18,Other Provider Identifier Type Code_18,Other Provider Identifier State_18,Other Provider Identifier Issuer_18,Other Provider Identifier_19,Other Provider Identifier Type Code_19,Other Provider Identifier State_19,Other Provider Identifier Issuer_19,Other Provider Identifier_20,Other Provider Identifier Type Code_20,Other Provider Identifier State_20,Other Provider Identifier Issuer_20,Other Provider Identifier_21,Other Provider Identifier Type Code_21,Other Provider Identifier State_21,Other Provider Identifier Issuer_21,Other Provider Identifier_22,Other Provider Identifier Type Code_22,Other Provider Identifier State_22,Other Provider Identifier Issuer_22,Other Provider Identifier_23,Other Provider Identifier Type Code_23,Other Provider Identifier State_23,Other Provider Identifier Issuer_23,Other Provider Identifier_24,Other Provider Identifier Type Code_24,Other Provider Identifier State_24,Other Provider Identifier Issuer_24,Other Provider Identifier_25,Other Provider Identifier Type Code_25,Other Provider Identifier State_25,Other Provider Identifier Issuer_25,Other Provider Identifier_26,Other Provider Identifier Type Code_26,Other Provider Identifier State_26,Other Provider Identifier Issuer_26,Other Provider Identifier_27,Other Provider Identifier Type Code_27,Other Provider Identifier State_27,Other Provider Identifier Issuer_27,Other Provider Identifier_28,Other Provider Identifier Type Code_28,Other Provider Identifier State_28,Other Provider Identifier Issuer_28,Other Provider Identifier_29,Other Provider Identifier Type Code_29,Other Provider Identifier State_29,Other Provider Identifier Issuer_29,Other Provider Identifier_30,Other Provider Identifier Type Code_30,Other Provider Identifier State_30,Other Provider Identifier Issuer_30,Other Provider Identifier_31,Other Provider Identifier Type Code_31,Other Provider Identifier State_31,Other Provider Identifier Issuer_31,Other Provider Identifier_32,Other Provider Identifier Type Code_32,Other Provider Identifier State_32,Other Provider Identifier Issuer_32,Other Provider Identifier_33,Other Provider Identifier Type Code_33,Other Provider Identifier State_33,Other Provider Identifier Issuer_33,Other Provider Identifier_34,Other Provider Identifier Type Code_34,Other Provider Identifier State_34,Other Provider Identifier Issuer_34,Other Provider Identifier_35,Other Provider Identifier Type Code_35,Other Provider Identifier State_35,Other Provider Identifier Issuer_35,Other Provider Identifier_36,Other Provider Identifier Type Code_36,Other Provider Identifier State_36,Other Provider Identifier Issuer_36,Other Provider Identifier_37,Other Provider Identifier Type Code_37,Other Provider Identifier State_37,Other Provider Identifier Issuer_37,Other Provider Identifier_38,Other Provider Identifier Type Code_38,Other Provider Identifier State_38,Other Provider Identifier Issuer_38,Other Provider Identifier_39,Other Provider Identifier Type Code_39,Other Provider Identifier State_39,Other Provider Identifier Issuer_39,Other Provider Identifier_40,Other Provider Identifier Type Code_40,Other Provider Identifier State_40,Other Provider Identifier Issuer_40,Other Provider Identifier_41,Other Provider Identifier Type Code_41,Other Provider Identifier State_41,Other Provider Identifier Issuer_41,Other Provider Identifier_42,Other Provider Identifier Type Code_42,Other Provider Identifier State_42,Other Provider Identifier Issuer_42,Other Provider Identifier_43,Other Provider Identifier Type Code_43,Other Provider Identifier State_43,Other Provider Identifier Issuer_43,Other Provider Identifier_44,Other Provider Identifier Type Code_44,Other Provider Identifier State_44,Other Provider Identifier Issuer_44,Other Provider Identifier_45,Other Provider Identifier Type Code_45,Other Provider Identifier State_45,Other Provider Identifier Issuer_45,Other Provider Identifier_46,Other Provider Identifier Type Code_46,Other Provider Identifier State_46,Other Provider Identifier Issuer_46,Other Provider Identifier_47,Other Provider Identifier Type Code_47,Other Provider Identifier State_47,Other Provider Identifier Issuer_47,Other Provider Identifier_48,Other Provider Identifier Type Code_48,Other Provider Identifier State_48,Other Provider Identifier Issuer_48,Other Provider Identifier_49,Other Provider Identifier Type Code_49,Other Provider Identifier State_49,Other Provider Identifier Issuer_49,Other Provider Identifier_50,Other Provider Identifier Type Code_50,Other Provider Identifier State_50,Other Provider Identifier Issuer_50,Is Sole Proprietor,Is Organization Subpart,Parent Organization LBN,Parent Organization TIN,Authorized Official Name Prefix Text,Authorized Official Name Suffix Text,Authorized Official Credential Text,Healthcare Provider Taxonomy Group_1,Healthcare Provider Taxonomy Group_2,Healthcare Provider Taxonomy Group_3,Healthcare Provider Taxonomy Group_4,Healthcare Provider Taxonomy Group_5,Healthcare Provider Taxonomy Group_6,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15,Certification Date
0,1679576722,1.0,NaN,NaN,NaN,WIEBE,DAVID,A,NaN,NaN,M.D.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PO BOX 2168,NaN,KEARNEY,NE,688482168.0,US,3.088653e+09,3.088653e+09,3500 CENTRAL AVE,NaN,KEARNEY,NE,688472944.0,US,3.088653e+09,3.088653e+09,05/23/2005,07/08/2007,NaN,NaN,NaN,M,NaN,NaN,NaN,NaN,NaN,207X00000X,12637,NE,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,645540,1.0,KS,FIRSTGUARD,46969,1.0,KS,BCBS,1553,1.0,NE,BCBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1588667638,1.0,NaN,NaN,NaN,PILCHER,WILLIAM,C,DR.,NaN,MD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1824 KING STREET,SUITE 300,JACKSONVILLE,FL,322044736.0,US,9.043882e+09,9.043882e+09,1824 KING STREET,SUITE 300,JACKSONVILLE,FL,322044736.0,US,9.043882e+09,9.043882e+09,05/23/2005,05/29/2014,NaN,NaN,NaN,M,NaN,NaN,NaN,NaN,NaN,207RC0000X,ME68414,FL,Y,207RC0000X,032024,GA,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00532485C,5.0,GA,NaN,510265,1.0,GA,BCBS,251286600,5.0,FL,NaN,27888,1.0,FL,BCBS,208143,1.0,FL,AVMED,00706626A,5.0,GA,NaN,897705.0,1.0,FL,AETNA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
col_list = profile.columns.to_list()
col_list

['NPI',
 'Entity Type Code',
 'Replacement NPI',
 'Employer Identification Number (EIN)',
 'Provider Organization Name (Legal Business Name)',
 'Provider Last Name (Legal Name)',
 'Provider First Name',
 'Provider Middle Name',
 'Provider Name Prefix Text',
 'Provider Name Suffix Text',
 'Provider Credential Text',
 'Provider Other Organization Name',
 'Provider Other Organization Name Type Code',
 'Provider Other Last Name',
 'Provider Other First Name',
 'Provider Other Middle Name',
 'Provider Other Name Prefix Text',
 'Provider Other Name Suffix Text',
 'Provider Other Credential Text',
 'Provider Other Last Name Type Code',
 'Provider First Line Business Mailing Address',
 'Provider Second Line Business Mailing Address',
 'Provider Business Mailing Address City Name',
 'Provider Business Mailing Address State Name',
 'Provider Business Mailing Address Postal Code',
 'Provider Business Mailing Address Country Code (If outside U.S.)',
 'Provider Business Mailing Address Telephone Number',
 'Provider Business Mailing Address Fax Number',
 'Provider First Line Business Practice Location Address',
 'Provider Second Line Business Practice Location Address',
 'Provider Business Practice Location Address City Name',
 'Provider Business Practice Location Address State Name',
 'Provider Business Practice Location Address Postal Code',
 'Provider Business Practice Location Address Country Code (If outside U.S.)',
 'Provider Business Practice Location Address Telephone Number',
 'Provider Business Practice Location Address Fax Number',
 'Provider Enumeration Date',
 'Last Update Date',
 'NPI Deactivation Reason Code',
 'NPI Deactivation Date',
 'NPI Reactivation Date',
 'Provider Gender Code',
 'Authorized Official Last Name',
 'Authorized Official First Name',
 'Authorized Official Middle Name',
 'Authorized Official Title or Position',
 'Authorized Official Telephone Number',
 'Healthcare Provider Taxonomy Code_1',
 'Provider License Number_1',
 'Provider License Number State Code_1',
 'Healthcare Provider Primary Taxonomy Switch_1',
 'Healthcare Provider Taxonomy Code_2',
 'Provider License Number_2',
 'Provider License Number State Code_2',
 'Healthcare Provider Primary Taxonomy Switch_2',
 'Healthcare Provider Taxonomy Code_3',
 'Provider License Number_3',
 'Provider License Number State Code_3',
 'Healthcare Provider Primary Taxonomy Switch_3',
 'Healthcare Provider Taxonomy Code_4',
 'Provider License Number_4',
 'Provider License Number State Code_4',
 'Healthcare Provider Primary Taxonomy Switch_4',
 'Healthcare Provider Taxonomy Code_5',
 'Provider License Number_5',
 'Provider License Number State Code_5',
 'Healthcare Provider Primary Taxonomy Switch_5',
 'Healthcare Provider Taxonomy Code_6',
 'Provider License Number_6',
 'Provider License Number State Code_6',
 'Healthcare Provider Primary Taxonomy Switch_6',
 'Healthcare Provider Taxonomy Code_7',
 'Provider License Number_7',
 'Provider License Number State Code_7',
 'Healthcare Provider Primary Taxonomy Switch_7',
 'Healthcare Provider Taxonomy Code_8',
 'Provider License Number_8',
 'Provider License Number State Code_8',
 'Healthcare Provider Primary Taxonomy Switch_8',
 'Healthcare Provider Taxonomy Code_9',
 'Provider License Number_9',
 'Provider License Number State Code_9',
 'Healthcare Provider Primary Taxonomy Switch_9',
 'Healthcare Provider Taxonomy Code_10',
 'Provider License Number_10',
 'Provider License Number State Code_10',
 'Healthcare Provider Primary Taxonomy Switch_10',
 'Healthcare Provider Taxonomy Code_11',
 'Provider License Number_11',
 'Provider License Number State Code_11',
 'Healthcare Provider Primary Taxonomy Switch_11',
 'Healthcare Provider Taxonomy Code_12',
 'Provider License Number_12',
 'Provider License Number State Code_12',
 'Healthcare Provider Primary Taxonomy Switch_12',
 'Healthcare Provider Taxonomy Code_13',
 'Provider License Number_13',
 'Provider License Number State Code_13',
 'Healthcare Provider Primary Taxonomy Switch_13',
 'Healthcare Provider Taxonomy Code_14',
 'Provider License Number_14',
 'Provider License Number State Code_14',
 'Healthcare Provider Primary Taxonomy Switch_14',
 'Healthcare Provider Taxonomy Code_15',
 'Provider License Number_15',
 'Provider License Number State Code_15',
 'Healthcare Provider Primary Taxonomy Switch_15',
 'Other Provider Identifier_1',
 'Other Provider Identifier Type Code_1',
 'Other Provider Identifier State_1',
 'Other Provider Identifier Issuer_1',
 'Other Provider Identifier_2',
 'Other Provider Identifier Type Code_2',
 'Other Provider Identifier State_2',
 'Other Provider Identifier Issuer_2',
 'Other Provider Identifier_3',
 'Other Provider Identifier Type Code_3',
 'Other Provider Identifier State_3',
 'Other Provider Identifier Issuer_3',
 'Other Provider Identifier_4',
 'Other Provider Identifier Type Code_4',
 'Other Provider Identifier State_4',
 'Other Provider Identifier Issuer_4',
 'Other Provider Identifier_5',
 'Other Provider Identifier Type Code_5',
 'Other Provider Identifier State_5',
 'Other Provider Identifier Issuer_5',
 'Other Provider Identifier_6',
 'Other Provider Identifier Type Code_6',
 'Other Provider Identifier State_6',
 'Other Provider Identifier Issuer_6',
 'Other Provider Identifier_7',
 'Other Provider Identifier Type Code_7',
 'Other Provider Identifier State_7',
 'Other Provider Identifier Issuer_7',
 'Other Provider Identifier_8',
 'Other Provider Identifier Type Code_8',
 'Other Provider Identifier State_8',
 'Other Provider Identifier Issuer_8',
 'Other Provider Identifier_9',
 'Other Provider Identifier Type Code_9',
 'Other Provider Identifier State_9',
 'Other Provider Identifier Issuer_9',
 'Other Provider Identifier_10',
 'Other Provider Identifier Type Code_10',
 'Other Provider Identifier State_10',
 'Other Provider Identifier Issuer_10',
 'Other Provider Identifier_11',
 'Other Provider Identifier Type Code_11',
 'Other Provider Identifier State_11',
 'Other Provider Identifier Issuer_11',
 'Other Provider Identifier_12',
 'Other Provider Identifier Type Code_12',
 'Other Provider Identifier State_12',
 'Other Provider Identifier Issuer_12',
 'Other Provider Identifier_13',
 'Other Provider Identifier Type Code_13',
 'Other Provider Identifier State_13',
 'Other Provider Identifier Issuer_13',
 'Other Provider Identifier_14',
 'Other Provider Identifier Type Code_14',
 'Other Provider Identifier State_14',
 'Other Provider Identifier Issuer_14',
 'Other Provider Identifier_15',
 'Other Provider Identifier Type Code_15',
 'Other Provider Identifier State_15',
 'Other Provider Identifier Issuer_15',
 'Other Provider Identifier_16',
 'Other Provider Identifier Type Code_16',
 'Other Provider Identifier State_16',
 'Other Provider Identifier Issuer_16',
 'Other Provider Identifier_17',
 'Other Provider Identifier Type Code_17',
 'Other Provider Identifier State_17',
 'Other Provider Identifier Issuer_17',
 'Other Provider Identifier_18',
 'Other Provider Identifier Type Code_18',
 'Other Provider Identifier State_18',
 'Other Provider Identifier Issuer_18',
 'Other Provider Identifier_19',
 'Other Provider Identifier Type Code_19',
 'Other Provider Identifier State_19',
 'Other Provider Identifier Issuer_19',
 'Other Provider Identifier_20',
 'Other Provider Identifier Type Code_20',
 'Other Provider Identifier State_20',
 'Other Provider Identifier Issuer_20',
 'Other Provider Identifier_21',
 'Other Provider Identifier Type Code_21',
 'Other Provider Identifier State_21',
 'Other Provider Identifier Issuer_21',
 'Other Provider Identifier_22',
 'Other Provider Identifier Type Code_22',
 'Other Provider Identifier State_22',
 'Other Provider Identifier Issuer_22',
 'Other Provider Identifier_23',
 'Other Provider Identifier Type Code_23',
 'Other Provider Identifier State_23',
 'Other Provider Identifier Issuer_23',
 'Other Provider Identifier_24',
 'Other Provider Identifier Type Code_24',
 'Other Provider Identifier State_24',
 'Other Provider Identifier Issuer_24',
 'Other Provider Identifier_25',
 'Other Provider Identifier Type Code_25',
 'Other Provider Identifier State_25',
 'Other Provider Identifier Issuer_25',
 'Other Provider Identifier_26',
 'Other Provider Identifier Type Code_26',
 'Other Provider Identifier State_26',
 'Other Provider Identifier Issuer_26',
 'Other Provider Identifier_27',
 'Other Provider Identifier Type Code_27',
 'Other Provider Identifier State_27',
 'Other Provider Identifier Issuer_27',
 'Other Provider Identifier_28',
 'Other Provider Identifier Type Code_28',
 'Other Provider Identifier State_28',
 'Other Provider Identifier Issuer_28',
 'Other Provider Identifier_29',
 'Other Provider Identifier Type Code_29',
 'Other Provider Identifier State_29',
 'Other Provider Identifier Issuer_29',
 'Other Provider Identifier_30',
 'Other Provider Identifier Type Code_30',
 'Other Provider Identifier State_30',
 'Other Provider Identifier Issuer_30',
 'Other Provider Identifier_31',
 'Other Provider Identifier Type Code_31',
 'Other Provider Identifier State_31',
 'Other Provider Identifier Issuer_31',
 'Other Provider Identifier_32',
 'Other Provider Identifier Type Code_32',
 'Other Provider Identifier State_32',
 'Other Provider Identifier Issuer_32',
 'Other Provider Identifier_33',
 'Other Provider Identifier Type Code_33',
 'Other Provider Identifier State_33',
 'Other Provider Identifier Issuer_33',
 'Other Provider Identifier_34',
 'Other Provider Identifier Type Code_34',
 'Other Provider Identifier State_34',
 'Other Provider Identifier Issuer_34',
 'Other Provider Identifier_35',
 'Other Provider Identifier Type Code_35',
 'Other Provider Identifier State_35',
 'Other Provider Identifier Issuer_35',
 'Other Provider Identifier_36',
 'Other Provider Identifier Type Code_36',
 'Other Provider Identifier State_36',
 'Other Provider Identifier Issuer_36',
 'Other Provider Identifier_37',
 'Other Provider Identifier Type Code_37',
 'Other Provider Identifier State_37',
 'Other Provider Identifier Issuer_37',
 'Other Provider Identifier_38',
 'Other Provider Identifier Type Code_38',
 'Other Provider Identifier State_38',
 'Other Provider Identifier Issuer_38',
 'Other Provider Identifier_39',
 'Other Provider Identifier Type Code_39',
 'Other Provider Identifier State_39',
 'Other Provider Identifier Issuer_39',
 'Other Provider Identifier_40',
 'Other Provider Identifier Type Code_40',
 'Other Provider Identifier State_40',
 'Other Provider Identifier Issuer_40',
 'Other Provider Identifier_41',
 'Other Provider Identifier Type Code_41',
 'Other Provider Identifier State_41',
 'Other Provider Identifier Issuer_41',
 'Other Provider Identifier_42',
 'Other Provider Identifier Type Code_42',
 'Other Provider Identifier State_42',
 'Other Provider Identifier Issuer_42',
 'Other Provider Identifier_43',
 'Other Provider Identifier Type Code_43',
 'Other Provider Identifier State_43',
 'Other Provider Identifier Issuer_43',
 'Other Provider Identifier_44',
 'Other Provider Identifier Type Code_44',
 'Other Provider Identifier State_44',
 'Other Provider Identifier Issuer_44',
 'Other Provider Identifier_45',
 'Other Provider Identifier Type Code_45',
 'Other Provider Identifier State_45',
 'Other Provider Identifier Issuer_45',
 'Other Provider Identifier_46',
 'Other Provider Identifier Type Code_46',
 'Other Provider Identifier State_46',
 'Other Provider Identifier Issuer_46',
 'Other Provider Identifier_47',
 'Other Provider Identifier Type Code_47',
 'Other Provider Identifier State_47',
 'Other Provider Identifier Issuer_47',
 'Other Provider Identifier_48',
 'Other Provider Identifier Type Code_48',
 'Other Provider Identifier State_48',
 'Other Provider Identifier Issuer_48',
 'Other Provider Identifier_49',
 'Other Provider Identifier Type Code_49',
 'Other Provider Identifier State_49',
 'Other Provider Identifier Issuer_49',
 'Other Provider Identifier_50',
 'Other Provider Identifier Type Code_50',
 'Other Provider Identifier State_50',
 'Other Provider Identifier Issuer_50',
 'Is Sole Proprietor',
 'Is Organization Subpart',
 'Parent Organization LBN',
 'Parent Organization TIN',
 'Authorized Official Name Prefix Text',
 'Authorized Official Name Suffix Text',
 'Authorized Official Credential Text',
 'Healthcare Provider Taxonomy Group_1',
 'Healthcare Provider Taxonomy Group_2',
 'Healthcare Provider Taxonomy Group_3',
 'Healthcare Provider Taxonomy Group_4',
 'Healthcare Provider Taxonomy Group_5',
 'Healthcare Provider Taxonomy Group_6',
 'Healthcare Provider Taxonomy Group_7',
 'Healthcare Provider Taxonomy Group_8',
 'Healthcare Provider Taxonomy Group_9',
 'Healthcare Provider Taxonomy Group_10',
 'Healthcare Provider Taxonomy Group_11',
 'Healthcare Provider Taxonomy Group_12',
 'Healthcare Provider Taxonomy Group_13',
 'Healthcare Provider Taxonomy Group_14',
 'Healthcare Provider Taxonomy Group_15',
 'Certification Date']

In [25]:
profile.head()

,NPI,Endpoint Type,Endpoint Type Description,Endpoint,Affiliation,Endpoint Description,Affiliation Legal Business Name,Use Code,Use Description,Other Use Description,Content Type,Content Description,Other Content Description,Affiliation Address Line One,Affiliation Address Line Two,Affiliation Address City,Affiliation Address State,Affiliation Address Country,Affiliation Address Postal Code
0,1154324382,DIRECT,Direct Messaging Address,Richard.Close@SEP.EClinicalDirectPlus.com,N,NaN,NaN,DIRECT,Direct,NaN,NaN,NaN,NaN,500 N Hiatus,Ste 200,Pembroke Pines,FL,US,33026
1,1154324382,DIRECT,Direct Messaging Address,rclose13800@MHSDIRECT.NET,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3501 Johnson St,NaN,Hollywood,FL,US,330215421
2,1962405175,DIRECT,Direct Messaging Address,fredericstelzer@epgi.allscriptsdirect.net,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1501 N Cedar Crest Blvd,suite 110,Allentown,PA,US,181042309
3,1699778894,DIRECT,Direct Messaging Address,aawomolo@direct.iuhealth.org,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2401 W University Ave,NaN,Muncie,IN,US,47303
4,1396748596,DIRECT,Direct Messaging Address,CHRISTIANO.CALDEIRA@hca4.eclinicaldirectplus.com,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1345 W Bay Dr Ste 301,NaN,Largo,FL,US,337702264

In [35]:
taxes = profile.filter(regex = '^NPI$|(Taxonomy (Code|Switch))')  # only NPI or Taxonomy Code or Taxonomy Switch

In [36]:
taxes.head()

,NPI,Healthcare Provider Taxonomy Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Healthcare Provider Primary Taxonomy Switch_15
0,1679576722,207X00000X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1588667638,207RC0000X,Y,207RC0000X,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1497758544,251G00000X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1306849450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1215930367,174400000X,N,207RH0003X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
taxes_code_long = taxes.melt(id_vars = [col for col in taxes.columns if 'NPI' in col or 'Taxonomy Switch' in col],
               var_name = 'Taxonomy Code Number',
               value_name = 'Taxonomy Code')

In [42]:
taxes_code_long.head()

,NPI,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Primary Taxonomy Switch_15,Taxonomy Code Number,Taxonomy Code
0,1679576722,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare Provider Taxonomy Code_1,207X00000X
1,1588667638,Y,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare Provider Taxonomy Code_1,207RC0000X
2,1497758544,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare Provider Taxonomy Code_1,251G00000X
3,1306849450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare Provider Taxonomy Code_1,NaN
4,1215930367,N,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Healthcare Provider Taxonomy Code_1,174400000X

In [44]:
taxes_long = taxes_code_long.melt(id_vars = [col for col in taxes_code_long.columns if 'NPI' in col or 'Taxonomy Code' in col],
                     var_name = 'Taxonomy Switch Number',
                     value_name = 'Taxonomy Switch')

In [46]:
taxes_long

,NPI,Taxonomy Code Number,Taxonomy Code,Taxonomy Switch Number,Taxonomy Switch
0,1679576722,Healthcare Provider Taxonomy Code_1,207X00000X,Healthcare Provider Primary Taxonomy Switch_1,Y
1,1588667638,Healthcare Provider Taxonomy Code_1,207RC0000X,Healthcare Provider Primary Taxonomy Switch_1,Y
2,1497758544,Healthcare Provider Taxonomy Code_1,251G00000X,Healthcare Provider Primary Taxonomy Switch_1,Y
3,1306849450,Healthcare Provider Taxonomy Code_1,NaN,Healthcare Provider Primary Taxonomy Switch_1,NaN
4,1215930367,Healthcare Provider Taxonomy Code_1,174400000X,Healthcare Provider Primary Taxonomy Switch_1,N
...,...,...,...,...,...
22495,1649273673,Healthcare Provider Taxonomy Code_15,NaN,Healthcare Provider Primary Taxonomy Switch_15,NaN
22496,1083617013,Healthcare Provider Taxonomy Code_15,NaN,Healthcare Provider Primary Taxonomy Switch_15,NaN
22497,1992708929,Healthcare Provider Taxonomy Code_15,NaN,Healthcare Provider Primary Taxonomy Switch_15,NaN
22498,1801899836,Healthcare Provider Taxonomy Code_15,NaN,Healthcare Provider Primary Taxonomy Switch_15,NaN
22499,1710980743,Healthcare Provider Taxonomy Code_15,NaN,Healthcare Provider Primary Taxonomy Switch_15,NaN

In [47]:
taxes_long['Taxonomy Code Number'] = taxes_long['Taxonomy Code Number'].str.extract('(\d+)')
taxes_long['Taxonomy Switch Number'] = taxes_long['Taxonomy Switch Number'].str.extract('(\d+)')


taxes_long

,NPI,Taxonomy Code Number,Taxonomy Code,Taxonomy Switch Number,Taxonomy Switch
0,1679576722,1,207X00000X,1,Y
1,1588667638,1,207RC0000X,1,Y
2,1497758544,1,251G00000X,1,Y
3,1306849450,1,NaN,1,NaN
4,1215930367,1,174400000X,1,N
...,...,...,...,...,...
22495,1649273673,15,NaN,15,NaN
22496,1083617013,15,NaN,15,NaN
22497,1992708929,15,NaN,15,NaN
22498,1801899836,15,NaN,15,NaN
22499,1710980743,15,NaN,15,NaN

In [50]:
primary_taxes= (taxes_long[(taxes_long['Taxonomy Code Number']==taxes_long['Taxonomy Switch Number'])
                          &
                          (taxes_long['Taxonomy Switch']=='Y')]
                          .drop(columns=['Taxonomy Code Number', 'Taxonomy Switch Number'])
    )
                          
primary_taxes

             NPI Taxonomy Code Taxonomy Switch
0     1679576722    207X00000X               Y
1     1588667638    207RC0000X               Y
2     1497758544    251G00000X               Y
5     1023011178    251G00000X               Y
7     1841293990    231H00000X               Y
8     1750384806    207R00000X               Y
9     1669475711    208000000X               Y
10    1578566626    207Q00000X               Y
11    1487657532    207V00000X               Y
12    1396748448    363A00000X               Y
13    1205839354    207X00000X               Y
14    1114920261    207R00000X               Y
17    1841293891    208600000X               Y
18    1750384707    174400000X               Y
19    1669475612    363L00000X               Y
20    1578566527    207X00000X               Y
21    1487657433    293D00000X               Y
22    1396748349    207VE0102X               Y
23    1205839255    207RC0000X               Y
25    1922001973    1041C0700X               Y
26    1831192889    207R00000X               Y
30    1477556421    152W00000X               Y
32    1164425112    1835P1200X               Y
33    1073516027    207W00000X               Y
34    1982607933    174400000X               Y
39    1336142389    207P00000X               Y
40    1245233295    207R00000X               Y
41    1962405910    174400000X               Y
42    1871596825    207Q00000X               Y
44    1699778647    251E00000X               Y
45    1508869553    207Q00000X               Y
46    1417950460    207X00000X               Y
47    1225031271    207RN0300X               Y
48    1134122187    363L00000X               Y
50    1952304909    207R00000X               Y
51    1861495814    207VX0201X               Y
53    1689677635    208100000X               Y
54    1598768541    363LF0000X               Y
55    1407859457    183500000X               Y
56    1316940364    207R00000X               Y
57    1124021175    207P00000X               Y
58    1033112081    207RP1001X               Y
61    1649273681    367500000X               Y
62    1558364596    207R00000X               Y
63    1467455402    225XH1200X               Y
64    1376546317    208000000X               Y
65    1285637223    207Q00000X               Y
67    1003819046    207VG0400X               Y
68    1912900952    208D00000X               Y
71    1306849336    1223G0001X               Y
72    1215930243    213ES0103X               Y
74    1932102969    207V00000X               Y
75    1841293875    363LA2200X               Y
76    1750384780    207Q00000X               Y
77    1669475695    207W00000X               Y
78    1578566501    207V00000X               Y
79    1487657417    1041C0700X               Y
80    1396748323    183500000X               Y
81    1205839230    3416L0300X               Y
82    1114920147    251E00000X               Y
83    1922001957    207V00000X               Y
85    1740283779    207RE0101X               Y
87    1568465599    208600000X               Y
88    1477556405    207X00000X               Y
90    1295738227    207X00000X               Y
91    1104829134    207Y00000X               Y
92    1013910041    213ES0103X               Y
94    1730182767    213ES0103X               Y
96    1083617013    261QF0400X               Y
97    1992708929    261QA1903X               Y
98    1801899836    363AM0700X               Y
99    1710980743    207Q00000X               Y
1604  1215930367    207RH0003X               Y
1606  1932102084    207RC0000X               Y
1615  1023011079    251E00000X               Y
1616  1932102985    207Q00000X               Y
1624  1114920162    207R00000X               Y
1629  1568465516    208G00000X               Y
1631  1255334207    207RC0000X               Y
1636  1700889755    207W00000X               Y
1637  1619970662    363LP0200X               Y
1638  1427051473    314000000X               Y
1659  1942203997    363LA2200X               Y
1660  1851394803    213ES0103X               Y
1666  1194728139    363AM0700X               Y
1673  1023011053    3336C0003X               Y
1684  1831192863    261QX0203X               Y
1693  1821091851    273Y00000X               Y
1695  1649273673    207V00000X               Y
3227  1740283795    313M00000X               Y
3228  1659374601    207Q00000X               Y
4849  1043213093    3336H0001X               Y
4869  1720081763    3336C0003X               Y
9670  1497758429    207X00000X               Y

In [51]:
profile_cols=['NPI',
             'Entity Type Code',
             'Provider Organization Name (Legal Business Name)',
            'Provider Last Name (Legal Name)',
            'Provider First Name',
            'Provider Middle Name',
            'Provider Name Prefix Text',
            'Provider Name Suffix Text',
            'Provider Credential Text',
             'Provider First Line Business Practice Location Address',
            'Provider Second Line Business Practice Location Address',
            'Provider Business Practice Location Address City Name',
            'Provider Business Practice Location Address State Name',
            'Provider Business Practice Location Address Postal Code'   
    
             ] #makes a list

In [54]:
profile_cols

{'Entity Type Code',
 'NPI',
 'Provider Business Practice Location Address City Name',
 'Provider Business Practice Location Address Postal Code',
 'Provider Business Practice Location Address State Name',
 'Provider Credential Text',
 'Provider First Line Business Practice Location Address',
 'Provider First Name',
 'Provider Last Name (Legal Name)',
 'Provider Middle Name',
 'Provider Name Prefix Text',
 'Provider Name Suffix Text',
 'Provider Organization Name (Legal Business Name)',
 'Provider Second Line Business Practice Location Address'}

In [55]:
profile['Provider Business Practice Location Address Postal Code']=profile['Provider Business Practice Location Address Postal Code'].astype(str)

In [56]:
profile=profile.loc[:, profile_cols] #choose only specific columns (a list created previusly)

In [57]:
profile

,Provider Second Line Business Practice Location Address,Provider Business Practice Location Address Postal Code,Provider Name Suffix Text,Provider Name Prefix Text,Entity Type Code,Provider Middle Name,NPI,Provider Business Practice Location Address State Name,Provider First Line Business Practice Location Address,Provider Last Name (Legal Name),Provider Business Practice Location Address City Name,Provider First Name,Provider Organization Name (Legal Business Name),Provider Credential Text
0,NaN,688472944.0,NaN,NaN,1.0,A,1679576722,NE,3500 CENTRAL AVE,WIEBE,KEARNEY,DAVID,NaN,M.D.
1,SUITE 300,322044736.0,NaN,DR.,1.0,C,1588667638,FL,1824 KING STREET,PILCHER,JACKSONVILLE,WILLIAM,NaN,MD
2,NaN,283044552.0,NaN,NaN,2.0,NaN,1497758544,NC,3418 VILLAGE DR,NaN,FAYETTEVILLE,NaN,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN
3,NaN,nan,NaN,NaN,NaN,NaN,1306849450,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,770901243.0,NaN,DR.,1.0,NaN,1215930367,TX,17323 RED OAK DR,GRESSOT,HOUSTON,LAURENT,NaN,M.D.
5,NaN,945594515.0,NaN,NaN,2.0,NaN,1023011178,CA,414 S JEFFERSON ST,NaN,NAPA,NaN,COLLABRIA CARE,NaN
6,NaN,436151753.0,NaN,NaN,1.0,K,1932102084,OH,2940 N MCCORD RD,ADUSUMILLI,TOLEDO,RAVI,NaN,MD
7,NaN,100102547.0,NaN,NaN,1.0,NaN,1841293990,NY,425 E 25TH ST,WORTSMAN,NEW YORK,SUSAN,NaN,MA-CCC
8,NaN,794151148.0,NaN,DR.,1.0,NaN,1750384806,TX,808 JOLIET AVE UNIT 120,BISBEE,LUBBOCK,ROBERT,NaN,MD
9,NaN,774411548.0,NaN,NaN,1.0,SHENG,1669475711,TX,7629 TIKI DR,SUNG,FULSHEAR,BIN,NaN,M. D.
10,NaN,850073913.0,NaN,NaN,1.0,D.,1578566626,AZ,1205 S 7TH AVE,KUIPERS,PHOENIX,WARREN,NaN,MD
11,SUITE 205,730721810.0,NaN,DR.,1.0,L,1487657532,OK,3400 W TECUMSEH RD,HUEBERT,NORMAN,ALLISON,NaN,M.D.
12,NaN,13069.0,NaN,MS.,1.0,J,1396748448,NY,806 WEST BROADWAY ASSOCIATED MEDICAL PROFESSIO...,YOUNG-MAYKA,FULTON,CYNTHIA,NaN,P.A.
13,NaN,633664281.0,NaN,DR.,1.0,A,1205839354,MO,9323 PHOENIX VILLAGE PKWY,DIFILIPPO,O FALLON,EMIL,NaN,M.D.
14,STE 200,323088417.0,NaN,DR.,1.0,RANDALL,1114920261,FL,2770 CAPITAL MEDICAL BLVD,THACKER,TALLAHASSEE,RICHARD,NaN,D.O.
15,SUITE F,604508812.0,NaN,NaN,2.0,NaN,1023011079,IL,425 E. US RT. 6,NaN,MORRIS,NaN,"ADVANTAGE HOME HEALTH CARE, INC.",NaN
16,SUITE 350,457012857.0,NaN,DR.,1.0,TERRY,1932102985,OH,75 HOSPITAL DR,ROTHSTEIN,ATHENS,MARK,NaN,M.D.
17,NaN,385552854.0,NaN,DR.,1.0,RICKEY,1841293891,TN,49 CLEVELAND ST 310,GIBBS,CROSSVILLE,ELMER,NaN,M.D.
18,NaN,554314800.0,NaN,DR.,1.0,WILLIAM,1750384707,MN,8100 NORTHLAND DR,MARKMAN,MINNEAPOLIS,ALAN,NaN,M.D.
19,NaN,891481502.0,NaN,NaN,1.0,CHARLENE,1669475612,NV,8876 SPANISH RIDGE AVE STE 103,TROTCHIE,LAS VEGAS,DEBRA,NaN,APN
20,STE 200,300609403.0,NaN,NaN,1.0,H,1578566527,GA,300 TOWER RD NE,DYSART,MARIETTA,STANLEY,NaN,M.D.
21,NaN,615545038.0,NaN,NaN,2.0,NaN,1487657433,IL,1300 PARK AVE,NaN,PEKIN,NaN,"PEKIN MRI, LLC",NaN
22,HOUSTON FERTILITY SPECIALISTS PLLC,770542935.0,NaN,DR.,1.0,M,1396748349,TX,7900 FANNIN ST STE 4000,GRUNERT,HOUSTON,GEORGE,NaN,M.D.
23,STE 110,110215306.0,NaN,DR.,1.0,M,1205839255,NY,1010 NORTHERN BLVD,GOLDBERG,GREAT NECK,STEVEN,NaN,M.D.
24,NaN,278862011.0,NaN,DR.,1.0,NaN,1114920162,NC,111 HOSPITAL DR,DUBOSE,TARBORO,JON,NaN,MD
25,NaN,560072919.0,NaN,MS.,1.0,MARY,1922001973,MN,216 E MAIN ST,ANDERSON-KRULL,ALBERT LEA,TERESA,NaN,MSW LICSW
26,NaN,363031928.0,NaN,NaN,1.0,L.,1831192889,AL,210 WESTSIDE DR,COE,DOTHAN,CRAIG,NaN,MD
27,NaN,500363930.0,NaN,NaN,2.0,NaN,1740283795,IA,715 W 3RD ST,NaN,BOONE,NaN,EASTERN STAR MASONIC HOME,NaN
28,STE 1F,376603365.0,NaN,NaN,1.0,TIPTON,1659374601,TN,105 W STONE DR,OBERDICK,KINGSPORT,WENDY,NaN,MD
29,NaN,212047736.0,NaN,NaN,1.0,NaN,1568465516,MD,7505 OSLER DR,SALENGER,TOWSON,RAWN,NaN,M.D.
30,STE 722,80511606.0,NaN,DR.,1.0,S.,1477556421,NJ,1107 MANTUA PIKE,ROTH,MANTUA,STEVEN,NaN,O.D.
31,NaN,61051208.0,NaN,NaN,1.0,NaN,1255334207,CT,114 WOODLAND ST,SOUCIER,HARTFORD,RICHARD,NaN,MD
32,RM 7-175,554550353.0,NaN,DR.,1.0,JOHN,1164425112,MN,308 HARVARD ST SE,ISETTS,MINNEAPOLIS,BRIAN,NaN,"B.C.P.S., PH.D."
33,NaN,109652029.0,NaN,DR.,1.0,CHU-HONG,1073516027,NY,169 N MIDDLETOWN RD,CHANG,PEARL RIVER,JOHN,NaN,M.D.
34,NaN,215021950.0,NaN,NaN,2.0,NaN,1982607933,MD,952 SETON DR,NaN,CUMBERLAND,NaN,ADR LLC,NaN
35,NaN,nan,NaN,NaN,NaN,NaN,1891798849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,STE 1,218041884.0,NaN,NaN,2.0,NaN,1700889755,MD,31519 WINTERPLACE PKWY,NaN,SALISBURY,NaN,AZAR/FILIPOV MD PA,NaN
37,NaN,782073108.0,NaN,MRS.,1.0,AMY,1619970662,TX,333 N SANTA ROSA,FRIEDMAN,SAN ANTONIO,LISA,NaN,"RN, MSN, CPNP"
38,NaN,494311908.0,NaN,NaN,2.0,NaN,1427051473,MI,1001 DIANA ST,NaN,LUDINGTON,NaN,OAKVIEW MEDICAL CARE FACILITY,NaN
39,NaN,134131068.0,NaN,NaN,2.0,NaN,1336142389,NY,1656 CHAMPLIN AVE,NaN,NEW HARTFORD,NaN,ADIRONDACK MEDICAL HEALTH CARE ASSOCIATES PLLC,NaN
40,NaN,144241728.0,NaN,DR.,1.0,K,1245233295,NY,335 PARRISH ST,POTTS,CANANDAIGUA,JILL,NaN,M.D.
41,STE 305,352051248.0,NaN,NaN,2.0,NaN,1962405910,AL,2700 10TH AVE S,NaN,BIRMINGHAM,NaN,"ALABAMA CARDIOVASCULAR GROUP, P.C.",NaN
42,NaN,547292104.0,NaN,DR.,1.0,JOHN,1871596825,WI,716 W COLUMBIA ST,WOLTER,CHIPPEWA FALLS,TIMOTHY,NaN,MD
43,STE 235,130901660.0,NaN,DR.,1.0,BETH,1780687731,NY,8100 OSWEGO RD,STAUBSINGER,LIVERPOOL,ARLENE,NaN,PH.D.
44,NaN,333194509.0,NaN,NaN,2.0,NaN,1699778647,FL,4291 ROCK ISLAND RD,NaN,LAUDERHILL,NaN,"VISITING HOME HEALTH SERVICES, INC",NaN
45,NaN,80941137.0,NaN,NaN,1.0,ANN,1508869553,NJ,220 PINE ST,VAN HOUTEN-SAUTER,WILLIAMSTOWN,LEE,NaN,D.O.
46,SUITE 200,875054728.0,NaN,DR.,1.0,A,1417950460,NM,1631 HOSPITAL DR,GARCIA,SANTA FE,JOHN,NaN,M.D.
47,STE 7,283749023.0,NaN,DR.,1.0,DAVID,1225031271,NC,293 OLMSTED BLVD,SHEPHERD,PINEHURST,JOHN,NaN,MD
48,STE 412,372031632.0,NaN,MRS.,1.0,DENISE,1134122187,TN,250 25TH AVE N,RUDNICKE,NASHVILLE,CHERYL,NaN,CRNP
49,NaN,72401.0,NaN,NaN,2.0,NaN,1043213093,AR,200 S MAIN ST,NaN,JONESBORO,NaN,HOME I V SPECIALISTS INC,NaN
50,SUITE 102,189511272.0,NaN,DR.,1.0,NaN,1952304909,PA,99 N WEST END BLVD,VASTA,QUAKERTOWN,ALFRED,NaN,M.D.
51,STE 302,341101497.0,NaN,DR.,1.0,ALBERTO,1861495814,FL,1660 MEDICAL BLVD,SMITH,NAPLES,FRANCISCO,NaN,M.D.
52,NaN,nan,NaN,NaN,NaN,NaN,1770586729,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,ATRIUM MEDICAL CENTER,450052584.0,NaN,DR.,1.0,WILLIAM,1689677635,OH,1 MEDICAL CENTER DR,DURITSCH,MIDDLETOWN,STEPHEN,NaN,M.D.
54,NaN,782151201.0,NaN,MS.,1.0,E.,1598768541,TX,1702 N ALAMO ST,ARENAS,SAN ANTONIO,BERTHA,NaN,FNP
55,SUITE 50,495462177.0,NaN,MR.,1.0,A.,1407859457,MI,4021 CASCADE RD SE,MAGNIFICO,GRAND RAPIDS,THOMAS,NaN,RPH
56,SUITE 350,457012857.0,NaN,DR.,1.0,NaN,1316940364,OH,75 HOSPITAL DR,CONJEEVARAM,ATHENS,GEETHA,NaN,M.D.
57,NaN,891280436.0,NaN,NaN,1.0,L,1124021175,NV,3100 N TENAYA WAY,TRIPPI,LAS VEGAS,DANA,NaN,D.O.
58,NaN,278345704.0,NaN,DR.,1.0,PATRICK,1033112081,NC,1850 W ARLINGTON BLVD,FOGARTY,GREENVILLE,JOHN,NaN,MD
59,SUITE 202,431303312.0,NaN,NaN,1.0,M,1942203997,OH,618 PLEASANTVILLE RD,MYERS,LANCASTER,JACQUELINE,NaN,"AND, BSN, MS, ANP"
60,SUITE 102,841174961.0,NaN,NaN,1.0,D,1851394803,UT,999 E MURRAY HOLLADAY RD,HARPER,SALT LAKE CITY,SPENCE,NaN,DPM
61,NaN,761026026.0,NaN,NaN,1.0,NaN,1649273681,TX,1401 HENDERSON ST,RENOUF,FORT WORTH,ROSE ANN,NaN,CRNA
62,STE. 110-507,891414371.0,NaN,NaN,1.0,NaN,1558364596,NV,10620 SOUTHERN HIGHLANDS PKWY,AKBAR,LAS VEGAS,TANVEER,NaN,MD
63,SUITE 100,853957804.0,NaN,MR.,1.0,A,1467455402,AZ,3050 N LITCHFIELD RD,MCCOY,GOODYEAR,SCOTT,NaN,OT
64,NaN,402913040.0,III,NaN,1.0,K,1376546317,KY,6425 BARDSTOWN RD,ALLGEIER,LOUISVILLE,MAURICE,NaN,MD
65,NaN,80941137.0,NaN,NaN,1.0,MICHAEL,1285637223,NJ,220 PINE ST,LOWRY,WILLIAMSTOWN,STEVEN,NaN,D.O.
66,2180 MAIN STREET,96793.0,NaN,MRS.,1.0,S,1194728139,HI,MAUI MEDICAL GROUP,STEWART,WAILUKU,SUSAN,NaN,P.A.-C
67,SUITE 209,372031513.0,NaN,NaN,1.0,H,1003819046,TN,345 23RD AVE N,NYLANDER,NASHVILLE,BARBARA,NaN,M.D.
68,STE 1,223021200.0,NaN,NaN,1.0,C,1912900952,VA,3450 N BEAUREGARD ST,KAUFFMAN,ALEXANDRIA,STEPHEN,NaN,M.D.
69,NaN,401430675.0,NaN,NaN,2.0,NaN,1720081763,KY,675 EAST HWY 60,NaN,HARDINSBURG,NaN,TOWNE & COUNTRY PHARMACY FLORIST & GIFTS INC,NaN
70,NaN,468044133.0,NaN,NaN,2.0,NaN,1497758429,IN,7601 W JEFFERSON BLVD,NaN,FORT WAYNE,NaN,FORT WAYNE ORTHOPAEDICS LLC,NaN
71,STE A,320825229.0,NaN,DR.,1.0,L,1306849336,FL,105 SOLANA RD,TOWNSEND,PONTE VEDRA,ERIC,NaN,DDS
72,NaN,226016453.0,NaN,DR.,1.0,LLOYD,1215930243,VA,650 CEDAR CREEK GRADE STE 108,VINCENT,WINCHESTER,ANDREW,NaN,D.P.M.
73,STE 11,900381662.0,NaN,NaN,2.0,NaN,1023011053,CA,1253 N VINE ST,NaN,LOS ANGELES,NaN,VINE DISCOUNT PHARMACY & MEDICAL SUPPLY,NaN
74,NaN,618203981.0,NaN,DR.,1.0,G,1932102969,IL,101 W UNIVERSITY AVE,HELFER,CHAMPAIGN,TAMARA,NaN,M.D.
75,SUITE 800,752314388.0,NaN,NaN,1.0,SUZANNE,1841293875,TX,8144 WALNUT HILL LN,MARTIN,DALLAS,ANDREA,NaN,"RN, MSN, FNP-C"
76,NaN,370551303.0,NaN,DR.,1.0,A,1750384780,TN,219 CHURCH ST,PERRIGIN,DICKSON,JULIE,NaN,MD
77,NaN,394023107.0,NaN,DR.,1.0,BRYCE,1669475695,MS,1420 S 28TH AVE,MCMAHAN,HATTIESBURG,LYNN,NaN,M.D.
78,STE 315,770822437.0,NaN,DR.,1.0,H,1578566501,TX,12121 RICHMOND AVE,LA,HOUSTON,BAO QUOC,NaN,M.D.
79,NaN,465803163.0,NaN,NaN,1.0,W,1487657417,IN,850 N HARRISON ST,CAREY,WARSAW,DANIEL,NaN,"MSW, LCSW"
80,NaN,37711.0,NaN,DR.,1.0,IVEY,1396748323,TN,272 HIGHWAY 11 E,CAMPBELL,BULLS GAP,LAURA,NaN,PHARMD
81,NaN,750013282.0,NaN,NaN,2.0,NaN,1205839230,TX,15401 ADDISON RD,NaN,ADDISON,NaN,"MERCY EMS, LLC",NaN
82,NaN,566492208.0,NaN,NaN,2.0,NaN,1114920147,MN,900 3RD ST,NaN,INTERNATIONAL FALLS,NaN,RIVER OAKS HOME HEALTH CARE LLC,NaN
83,STE 302,372032023.0,NaN,NaN,1.0,E,1922001957,TN,2011 MURPHY AVE,PRESLEY,NASHVILLE,RICHARD,NaN,M.D.
84,NaN,761044110.0,NaN,NaN,2.0,NaN,1831192863,TX,1450 8TH AVE,NaN,FORT WORTH,NaN,MONCRIEF CANCER CENTER,NaN
85,SUITE 4310,61051770.0,NaN,NaN,1.0,NaN,1740283779,CT,1000 ASYLUM AVE,JAVIER,HARTFORD,EMMANUEL,NaN,MD
86,STE 140,445128070.0,NaN,NaN,2.0,NaN,1659374684,OH,1449 BOARDMAN CANFIELD RD,NaN,BOARDMAN,NaN,NYDIC OPEN MRI OF AMERICA-BOARDMAN,NaN
87,STE 2550,40112681.0,NaN,NaN,1.0,NaN,1568465599,ME,121 MEDICAL CENTER DR,HYDE,BRUNSWICK,NATHANIEL,NaN,M.D.
88,STE 100,633012881.0,NaN,DR.,1.0,M,1477556405,MO,400 1ST CAPITOL DR,LINSENMEYER,SAINT CHARLES,CHARLES,NaN,M.D.
89,NaN,nan,NaN,NaN,NaN,NaN,1386647311,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,STE 200,300609403.0,NaN,NaN,1.0,NaN,1295738227,GA,300 TOWER RD NE,DAY,MARIETTA,JOHN,NaN,M.D.
91,NaN,376642371.0,NaN,DR.,1.0,NaN,1104829134,TN,1728 N EASTMAN RD,FALCONER,KINGSPORT,RANDALL,NaN,MD
92,NaN,468044133.0,NaN,DR.,1.0,NaN,1013910041,IN,7601 W JEFFERSON BLVD,DETOMMASO,FORT WAYNE,DOMINICK,NaN,D.P.M.
93,NaN,283043424.0,NaN,NaN,2.0,NaN,1821091851,NC,1638 OWEN DR,NaN,FAYETTEVILLE,NaN,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN
94,NaN,931053805.0,NaN,DR.,1.0,LEE,1730182767,CA,222 W PUEBLO ST,SCHLEGEL,SANTA BARBARA,GARY,NaN,DPM
95,SUITE 300,281052387.0,NaN,NaN,1.0,M,1649273673,NC,1450 MATTHEWS TOWNSHIP PKWY,KOPCZYNSKI,MATTHEWS,TODD,NaN,M.D.
96,NaN,31011325.0,NaN,NaN,2.0,NaN,1083617013,NH,145 HOLLIS ST,NaN,MANCHESTER,NaN,AMOSKEAG HEALTH,NaN
97,STE 200,303271610.0,NaN,NaN,2.0,NaN,1992708929,GA,3200 DOWNWOOD CIR NW,NaN,ATLANTA,NaN,NOVAMED MANAGEMENT SERVICES LLC,NaN
98,SUITE 410,958165120.0,NaN,MRS.,1.0,L,1801899836,CA,2801 K ST,ZICHELLA,SACRAMENTO,SARAH,NaN,PA-C
99,NaN,890745889.0,NaN,NaN,1.0,C,1710980743,NV,1701N GREEN VALLEY PKWY 5C,ALLEN,HENDERSON,EVAN,NaN,MD

# Merge

In [58]:
profile=pd.merge(profile,primary_taxes)
profile.head(5)

,Provider Second Line Business Practice Location Address,Provider Business Practice Location Address Postal Code,Provider Name Suffix Text,Provider Name Prefix Text,Entity Type Code,Provider Middle Name,NPI,Provider Business Practice Location Address State Name,Provider First Line Business Practice Location Address,Provider Last Name (Legal Name),Provider Business Practice Location Address City Name,Provider First Name,Provider Organization Name (Legal Business Name),Provider Credential Text,Taxonomy Code,Taxonomy Switch
0,NaN,688472944.0,NaN,NaN,1.0,A,1679576722,NE,3500 CENTRAL AVE,WIEBE,KEARNEY,DAVID,NaN,M.D.,207X00000X,Y
1,SUITE 300,322044736.0,NaN,DR.,1.0,C,1588667638,FL,1824 KING STREET,PILCHER,JACKSONVILLE,WILLIAM,NaN,MD,207RC0000X,Y
2,NaN,283044552.0,NaN,NaN,2.0,NaN,1497758544,NC,3418 VILLAGE DR,NaN,FAYETTEVILLE,NaN,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN,251G00000X,Y
3,NaN,770901243.0,NaN,DR.,1.0,NaN,1215930367,TX,17323 RED OAK DR,GRESSOT,HOUSTON,LAURENT,NaN,M.D.,207RH0003X,Y
4,NaN,945594515.0,NaN,NaN,2.0,NaN,1023011178,CA,414 S JEFFERSON ST,NaN,NAPA,NaN,COLLABRIA CARE,NaN,251G00000X,Y

In [59]:
profile.columns = [c.replace(' ', '_') for c in profile.columns]
profile.columns

Index(['Provider_Second_Line_Business_Practice_Location_Address',
       'Provider_Business_Practice_Location_Address_Postal_Code',
       'Provider_Name_Suffix_Text', 'Provider_Name_Prefix_Text',
       'Entity_Type_Code', 'Provider_Middle_Name', 'NPI',
       'Provider_Business_Practice_Location_Address_State_Name',
       'Provider_First_Line_Business_Practice_Location_Address',
       'Provider_Last_Name_(Legal_Name)',
       'Provider_Business_Practice_Location_Address_City_Name',
       'Provider_First_Name',
       'Provider_Organization_Name_(Legal_Business_Name)',
       'Provider_Credential_Text', 'Taxonomy_Code', 'Taxonomy_Switch'],
      dtype='object')

In [60]:
taxonomy_code=pd.read_csv('./data/NPPES/nucc_taxonomy_220.csv')
taxonomy_code.head(5)

,Code,Grouping,Classification,Specialization,Definition,Notes,Display Name,Section
0,193200000X,Group,Multi-Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Multi-Specialty Group,Individual
1,193400000X,Group,Single Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Single Specialty Group,Individual
2,207K00000X,Allopathic & Osteopathic Physicians,Allergy & Immunology,NaN,An allergist-immunologist is trained in evalua...,"Source: American Board of Medical Specialties,...",Allergy & Immunology Physician,Individual
3,207KA0200X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Allergy,Definition to come...,NaN,Allergy Physician,Individual
4,207KI0005X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Clinical & Laboratory Immunology,Definition to come...,NaN,Clinical & Laboratory Immunology (Allergy & Im...,Individual

# Create a SQL database and add the dfs as tables to it

In [62]:
db = sqlite3.connect('./data/hopteam.sqlite')  # connect to a sql database named as hopteam (create)

In [63]:
profile.to_sql('profile', db, if_exists='append', index=False) # if such a table exists, just append data to it
from_npi.to_sql('referral_from', db, if_exists = 'append', index = False) # ignore the existing index and creat new index in teh database
to_npi.to_sql('referral_to', db, if_exists = 'append', index = False)
referrals.to_sql('referrals', db, if_exists = 'append', index = False)
cbsa_zip.to_sql('zip_cbsa', db, if_exists = 'append', index = False)
taxonomy_code.to_sql('taxonomy_code', db, if_exists='append', index=False )

/Users/ntaherkh/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:2779: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(

In [ ]:
db.close()