In [8]:
import pandas as pd
import sqlite3
import numpy as np
import sqlite3
from tqdm.notebook import tqdm
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [12]:
db = sqlite3.connect('../data/hopteam.sqlite')

In [13]:
queries = ["""
        ALTER TABLE taxonomy
        RENAME COLUMN Code TO code;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN Grouping TO grouping;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN Classification TO classification;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN Specialization TO specialization;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN Definition TO definition;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN Notes TO notes;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN "Display Name" TO display_name;
        """,
        """
        ALTER TABLE taxonomy
        RENAME COLUMN Section TO section;
        """
        ]
for query in queries:
    db.execute(query)

In [14]:
db.close()

In [ ]:
with sqlite3.connect('../data/hopteam.sqlite') as db: 
    db.execute('CREATE INDEX npi ON profile(npi)')
    db.execute('CREATE INDEX to_npi ON referral_to(to_npi)')
    db.execute('CREATE INDEX referral_id ON referrals(referral_id)')
    db.execute('CREATE INDEX from_npi ON referral_from(from_npi)')
    db.execute('CREATE INDEX code ON taxonomy(code)')
    db.execute('CREATE INDEX zip ON zip_cbsa(zip)')
    db.execute('CREATE INDEX provider_business_practice_location_address_postal_code ON profile(provider_business_practice_location_address_postal_code)')
    db.execute('CREATE INDEX taxonomy_code ON profile(taxonomy_code)')
    db.execute('CREATE INDEX to_referral_id ON referral_to(referral_id)')

In [9]:
query = """
select *
from taxonomy
limit 5
"""

In [10]:
with sqlite3.connect('../data/hopteam.sqlite') as db: 
   hopteam = pd.read_sql(query, db)

In [11]:
hopteam

,Code,Grouping,Classification,Specialization,Definition,Notes,Display Name,Section
0,193200000X,Group,Multi-Specialty,None,A business group of one or more individual pra...,[7/1/2003: new],Multi-Specialty Group,Individual
1,193400000X,Group,Single Specialty,None,A business group of one or more individual pra...,[7/1/2003: new],Single Specialty Group,Individual
2,207K00000X,Allopathic & Osteopathic Physicians,Allergy & Immunology,None,An allergist-immunologist is trained in evalua...,"Source: American Board of Medical Specialties,...",Allergy & Immunology Physician,Individual
3,207KA0200X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Allergy,Definition to come...,None,Allergy Physician,Individual
4,207KI0005X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Clinical & Laboratory Immunology,Definition to come...,None,Clinical & Laboratory Immunology (Allergy & Im...,Individual